defaults:
  - _self_
  # - task: square_image_vel
  # - task: square_image_abs
  - task: pickcan_image_abs
  # - task: twoArmLift_image_vel
  # - task: twoArmLift_image_abs
  # - task: pushT_abs
  # - task: metaworld_hammer_vel

task_name: ${task.task_name}
experiment_id: ${AGENT.experiment_id}


GENERAL:
  # simulator and tasks
  environment: ${task.environment}
  use_abs_action: ${task.use_abs_action}
  use_image: ${task.use_image}
  task: ${task.task_name}


  save_results: true
  record_traj_dataset: false

  number_of_repetitions: ${task.number_of_repetitions}
  evaluations_per_training: ${task.evaluations_per_training}
  max_num_of_episodes: ${task.max_num_of_episodes}
  max_time_steps_episode: ${task.max_time_steps_episode}
  max_time_steps_per_repetition: ${task.max_time_steps_per_repetition}

  # feedback
  theta: 0.1  # threshold for each dimension of the oracle teacher's action
  feedback_threshold: ${task.feedback_threshold}
  oracle_teacher: true
  human_teacher: false


  # adding noise to the teacher action
  oracle_teacher_noise: 0   # directional noise angle
  if_biased_directional_noise: false
  oracle_teacher_magnitude_noise: false
  oracle_teacher_magnitude_noise_parameter: 0 # directional noise magnitude
  oracle_teacher_only_one_dim: false
  oracle_teacher_Gaussian_noise: false    # Gaussian noise
  # oracle_teacher_Gaussian_noise: true    # Gaussian noise

  Ta: 16  # horizon
  Ta_executed: 8
  # Ta: 4  # horizon
  # Ta_executed: 2

AGENT:
  use_hdf5_dataset: false
  use_abs_action: ${task.use_abs_action}
  use_image: ${task.use_image}
  image_crop_shape: ${task.crop_shape} # used in obs_encoder

  shape_meta: ${task.shape_meta}

  dim_a: ${task.dim_a}
  dim_o: ${task.dim_o}  # TODO define this in task.yaml

  e: ${task.e} # only define diagional
  loss_weight_inverse_e: ${task.loss_weight_inverse_e}
  policy_model_learning_rate: 0.0002
  # number_training_iterations: 300
  number_training_iterations: 1000

  Ta: ${GENERAL.Ta}  # horizon
  Ta_executed:  ${GENERAL.Ta_executed}

  agent: Set_Supervised_Diffusion # DPO uses the set-supervised diffusion selector path; only the loss function differs
  algorithm: Diffusion_DPO

    # DDPM
  DDPM_num_train_timesteps: 100
  use_DDIM_during_inference: true
  num_inference_steps: 16
  # use_DDIM_during_inference: false
  # num_inference_steps: 100
  diffusion_step_embed_dim: 128
  unet_down_dims: [512, 1024, 2048]

  use_AutoEncoder_loss: false
  # frozen_obs_encoder: true
  frozen_obs_encoder: false

  # desiredA_type: Half # select from [Half, Circular]
  desiredA_type: Circular # select from [Half, Circular]
  large_desiredA: false # for Ta>1, if true, treat the whole action chunk as a single action

  # parameters for desiredA_type = Half
  sphere_alpha: 30
  sphere_gamma: 0.9
  # parameters for desiredA_type = Circular
  radius_ratio: 0.1
  # radius_ratio: 0.9

  # sample actions during trainiong
  # sample_action_number: 128
  sample_action_number: 8
  sample_with_desiredA_reverse_start_t: 16
  # sample_with_desiredA_reverse_start_t: 16


  # Buffer
  buffer_max_size: 60000
  # buffer_min_size: 64
  buffer_min_size: 64
  buffer_sampling_rate: 20
  train_end_episode: true
  # buffer_sampling_size: 64
  buffer_sampling_size: 64
  action_upper_limits: 1
  action_lower_limits: -1


  # log
  save_policy: false  #also control whether we save data buffer
  save_buffer: false
  experiment_id: "${now:%Y%m%d_%H%M%S}_${AGENT.algorithm}_${AGENT.desiredA_type}_${task.name}_Ta${AGENT.Ta}_offline${AGENT.offline_training}"
  base_dir: saved_data/
  saved_dir: saved_data/
  load_policy: false
  # load_policy: true
  # load_dir: saved_data/robosuite_square/Diffusion_CLIC_intervention/

  # load dir: used for evaluate is true
  # load_pretrained_dir: used for offline_training is true
  # load_dir: outputs/2025-06-02/23-33-38CLIC-Diff-cir-abs-ta8/saved_data/robosuite_square/Diffusion_CLIC_intervention/0602_23_Circular_square_image_abs_Ta16_offlineTrue/repetition_000/
  # load_dir:  outputs/20250615_221845_Diffusion_CLIC_intervention_Circular_pushT_image_abs_Ta16_offlineFalse/ # delftblue
  load_dir: null
  # offline_training: true
  offline_training: false
  # evaluate the policy under saved_dir
  # evaluate: true
  evaluate: false
  # abs dataset
  load_pretrained_dir: null
  # load_pretrained_dir: outputs/20250615_221845_Diffusion_CLIC_intervention_Circular_pushT_image_abs_Ta16_offlineFalse/



FEEDBACK:
  use_space_mouse: false
