defaults:
  - _self_
  # - task: kuka_pushT_image_vel
  - task: kuka_pushT_image_abs
  # - task: kuka_6d_low_dim_vel
  # - task: kuka_pushT_low_dim_vel

task_name: ${task.task_name}
experiment_id: ${AGENT.experiment_id}

GENERAL:
  # simulator and tasks
  environment: ${task.environment}
  use_abs_action: ${task.use_abs_action}
  use_image: ${task.use_image}
  task: ${task.task_name}


  save_results: true

  number_of_repetitions: ${task.number_of_repetitions}
  evaluations_per_training: ${task.evaluations_per_training}
  max_num_of_episodes: ${task.max_num_of_episodes}
  max_time_steps_episode: ${task.max_time_steps_episode}
  max_time_steps_per_repetition: ${task.max_time_steps_per_repetition}

  # feedback
  theta: 0.1  # threshold for each dimension of the oracle teacher's action
  feedback_threshold: ${task.feedback_threshold}
  oracle_teacher: false
  human_teacher: true


  # adding noise to the teacher action
  oracle_teacher_noise: 0   # directional noise angle
  if_biased_directional_noise: false
  oracle_teacher_magnitude_noise: false
  oracle_teacher_magnitude_noise_parameter: 0 # directional noise magnitude
  oracle_teacher_only_one_dim: false
  oracle_teacher_Gaussian_noise: false    # Gaussian noise
  # oracle_teacher_Gaussian_noise: true    # Gaussian noise

  Ta: 1  # horizon
  Ta_executed: 1

AGENT:
  use_abs_action: ${task.use_abs_action}
  use_image: ${task.use_image}
  image_crop_shape: ${task.crop_shape} # used in obs_encoder

  shape_meta: ${task.shape_meta}

  dim_a: ${task.dim_a}
  dim_o: ${task.dim_o}  # TODO define this in task.yaml

  #TODO move this to task.yaml
  # e: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]  # only define diagional
  # loss_weight_inverse_e: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  # e: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]  # only define diagional
  e: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]  # only define diagional
  loss_weight_inverse_e: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  # e: [0.2, 0.2]  # only define diagional
  # loss_weight_inverse_e: [1.0, 1.0]
  policy_model_learning_rate: 0.0002
  number_training_iterations: 100
  # number_training_iterations: 240

  # Ta: 16
  # Ta_executed: 8
  Ta: ${GENERAL.Ta}  # horizon
  Ta_executed:  ${GENERAL.Ta_executed}

  agent: Set_Supervised_Diffusion
  algorithm: Set_Supervised_Diffusion_intervention

  # DDPM
  DDPM_num_train_timesteps: 25
  # use_DDIM_during_inference: false
  # num_inference_steps: ${AGENT.DDPM_num_train_timesteps}
  use_DDIM_during_inference: true
  num_inference_steps: 16

  # desiredA_type: Half # select from [Half, Circular]
  desiredA_type: Circular # select from [Half, Circular]
  # large_desiredA: true # for Ta>1, if true, treat the whole action chunk as a single action
  large_desiredA: false # for Ta>1, if true, treat the whole action chunk as a single action

  # parameters for desiredA_type = Half
  sphere_alpha: 30
  sphere_gamma: 0.9
  # parameters for desiredA_type = Circular
  radius_ratio: 0.1
  # radius_ratio: 0.9

  # sample actions during trainiong
  # sample_action_number: 128  # good for offline training
  sample_action_number: 64
  # sample_with_desiredA_reverse_start_t: 16  # good for offline training
  sample_with_desiredA_reverse_start_t: 8
  # Unet Policy decoder
  diffusion_step_embed_dim: 64
  unet_down_dims: [256, 512, 1024]

  # Buffer
  buffer_max_size: 60000
  buffer_min_size: 32
  buffer_sampling_rate: 20
  train_end_episode: true
  buffer_sampling_size: 32
  action_upper_limits: 1
  action_lower_limits: -1


  # log
  save_policy: true
  experiment_id: "${now:%m%d_%H}_${AGENT.desiredA_type}_${task.name}_Ta${AGENT.Ta}_offline${AGENT.offline_training}"
  base_dir: saved_data/robosuite_square/Diffusion_CLIC_intervention/
  saved_dir: saved_data/robosuite_square/Diffusion_CLIC_intervention/

  # load_dir: outputs/2025-06-05/20-17-56/saved_data/PushT/Diffusion_CLIC_intervention/0605_20_Circular_pushT_image_Ta1_offlineFalse/repetition_000/
  # load_dir: outputs_docker/0731_13_Circular_kuka-6d_Ta1_offlineFalse_2/repetition_000/
  load_dir: null
  # load_policy: true
  load_policy: false
  # load_dir: saved_data/robosuite_square/Diffusion_CLIC_intervention/

  offline_data_collection: false
  offline_training: false
  # offline_training: true
  # evaluate the policy under saved_dir
  evaluate: false
  ## vel dataset
  load_pretrained_dir: null
  ## abs dataset
  # load_pretrained_dir: saved_data/robosuite_square/Diffusion_CLIC_intervention/0601_abs_Ta1_img_Thre005_T100_E6_SA128_cir/repetition_000/


FEEDBACK:
  use_keyboard : true
  use_space_mouse: true
