defaults:
  - _self_
  # - task: square_image_vel
  - task: kuka_pushT_image_abs  # tested
  # - task: franka_6d_image_abs
  # - task: twoArmLift_image_vel
  # - task: twoArmLift_image_abs
  # - task: pushT_abs

task_name: ${task.task_name}
experiment_id: ${AGENT.experiment_id}

GENERAL:
  # simulator and tasks
  environment: ${task.environment}
  use_abs_action: ${task.use_abs_action}
  use_image: ${task.use_image}
  task: ${task.task_name}


  save_results: true

  number_of_repetitions: ${task.number_of_repetitions}
  evaluations_per_training: ${task.evaluations_per_training}
  max_num_of_episodes: ${task.max_num_of_episodes}
  max_time_steps_episode: ${task.max_time_steps_episode}
  max_time_steps_per_repetition: ${task.max_time_steps_per_repetition}

  # feedback
  theta: 0.1  # threshold for each dimension of the oracle teacher's action
  feedback_threshold: ${task.feedback_threshold}
  oracle_teacher: false
  human_teacher: true


  # adding noise to the teacher action
  oracle_teacher_noise: 0   # directional noise angle
  if_biased_directional_noise: false
  oracle_teacher_magnitude_noise: false
  oracle_teacher_magnitude_noise_parameter: 0 # directional noise magnitude
  oracle_teacher_only_one_dim: false
  # oracle_teacher_Gaussian_noise: false    # Gaussian noise
  oracle_teacher_Gaussian_noise: true    # Gaussian noise

  Ta: 16  # horizon
  Ta_executed: 8

AGENT:
  use_hdf5_dataset: true
  use_abs_action: ${task.use_abs_action}
  use_image: ${task.use_image}
  image_crop_shape: ${task.crop_shape} # used in obs_encoder

  shape_meta: ${task.shape_meta}

  dim_a: ${task.dim_a}
  dim_o: ${task.dim_o}  # TODO define this in task.yaml

  e: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]  # only define diagional
  loss_weight_inverse_e: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  policy_model_learning_rate: 0.0002
  number_training_iterations: 2000

  # Ta: 16
  # Ta_executed: 8
  Ta: ${GENERAL.Ta}  # horizon
  Ta_executed:  ${GENERAL.Ta_executed}

  agent: Diffusion
  algorithm: Diffusion_policy

  use_AutoEncoder_loss: true  # used during pre-training
  # use_AutoEncoder_loss: false
  # frozen_obs_encoder: true
  frozen_obs_encoder: false

  use_ambient_loss: false  # loss for Ambient Diffusion for linear corrupted data
  ambient_k: 3  # number of dimensions that should trust; for PushT, 1, for Square, 3 or 4, for TwoArm, 7


  # DDPM
  DDPM_num_train_timesteps: 100
  # use_DDIM_during_inference: false
  # num_inference_steps: ${AGENT.DDPM_num_train_timesteps}
  use_DDIM_during_inference: true
  num_inference_steps: 16
  # Unet Policy decoder
  diffusion_step_embed_dim: 64
  unet_down_dims: [256, 512, 1024]


  # Buffer
  buffer_max_size: 35000
  buffer_min_size: 16
  # buffer_min_size: 32
  # buffer_sampling_rate: 5
  train_end_episode: true
  buffer_sampling_size: 16
  # buffer_sampling_size: 32
  action_upper_limits: 1
  action_lower_limits: -1


  # log
  save_policy: true  #also control whether we save data buffer
  save_buffer: false
  experiment_id: "${now:%Y%m%d_%H%M%S}_${AGENT.algorithm}_${task.name}_Ta${AGENT.Ta}_offline${AGENT.offline_training}"
  base_dir: saved_data/
  saved_dir: saved_data/
  # load_policy: false
  load_policy: true
  # load_dir: saved_data/robosuite_square/Diffusion_CLIC_intervention/

  # load dir: used for evaluate is true
  # load_pretrained_dir: used for offline_training is true
  # load_dir: outputs/2025-06-02/23-33-38CLIC-Diff-cir-abs-ta8/saved_data/robosuite_square/Diffusion_CLIC_intervention/0602_23_Circular_square_image_abs_Ta16_offlineTrue/repetition_000/
  # load_dir:  outputs/20250615_221845_Diffusion_CLIC_intervention_Circular_pushT_image_abs_Ta16_offlineFalse/ # delftblue
  # load_dir:  outputs_docker/2025-21-55-02-InserT_70data_CLIC_DP_pretrained_91episodes/
  # load_dir:  outputs_docker/Training_Nov24_demo_corrections_CDP/saved_data/
  # load_dir:  outputs_docker/2025_1112_DP/
  load_dir:  outputs_docker/2025_1111_DP/

  # load_dir:  outputs_docker/Training_Nov19_demo_pretraining_CDP/saved_data/
  # load_dir:  outputs_docker/Training_Nov19_demo_pretraining_DP/saved_data/
  offline_training: true
  # offline_training: false
  # evaluate the policy under saved_dir
  # evaluate: true
  evaluate: false
  # abs dataset
  load_pretrained_dir: outputs/
  # load_pretrained_dir: saved_data/robosuite_square/Diffusion_CLIC_intervention/0601_abs_Ta8_img_Thre005_T100_E6_cir/repetition_000/
  # load_pretrained_dir: outputs/20250615_221845_Diffusion_CLIC_intervention_Circular_pushT_image_abs_Ta16_offlineFalse/
  # buffer_dataset_path: outputs_docker/trajectory_buffer_0929_InsertBlueT_GreenU_demonstration_73trajs.h5
  buffer_dataset_path: outputs_docker/data_buffer_Nov10_demo_noisy_shuffled.h5
  # buffer_dataset_path :
  #   - outputs_docker/data_buffer_Nov19_demo30_franka_shuffled.h5
  #   # - outputs_docker/data_buffer_0_demo30_nvo27_shuffled.h5
  #   - outputs_docker/data_buffer_02_03_04_internventionNov20_21_24.h5
  #   - outputs_docker/data_buffer_intervention_Nov25_relabeled_rmteacher_shuffled.h5
  # buffer_dataset_list_sample_ratio:
  #   - 0.5
  #   - 0.5

  # buffer_dataset_list_sample_ratio:
  #   - 0.3
  #   - 0.55
  #   - 0.15

  buffer_selfplay_dataset_path: outputs_docker/data_buffer_self_play1119_franka.h5
  # buffer_selfplay_dataset_path: outputs_docker/trajectory_buffer_self_play0930.h5
  # buffer_dataset_path: ${BD_COACH_DATA_ROOT}/CLIC_DP_real_exp_data/0930/trajectory_buffer_0929_InsertBlueT_GreenU_demonstration_73trajs_0930_Intervention.h5
  # buffer_selfplay_dataset_path: ${BD_COACH_DATA_ROOT}/CLIC_DP_real_exp_data/0930/trajectory_buffer_self_play0930.h5
  load_buffer_from_absolute_path: false


FEEDBACK:
  use_space_mouse: true
